description: This component retrieves the podcast using the Listen Notes API. It takes
  the podcast URL as an input and outputs the audio file of the podcast. The Listen
  Notes API is used to fetch the podcast details by passing the podcast URL, and then
  downloads the audio file associated with the podcast.
input-class: PodcastUrlInputDict
name: FetchPodcast
output-class: PodcastAudioFileOutputDict
parameters: {}
