description: 'This component summarizes the podcast transcript using the OpenAI ChatGPT
  API. Inputs: PodcastTranscript (from TranscribePodcast). Outputs: PodcastSummary
  (the summary text of the podcast).'
name: GenerateSummary
parameters: {}
