description: The Workflow requires a PodcastUrl as input (a subclass of pydantic.BaseModel
  with an attribute containing the podcast url as a string). The output is a TranscriptSummaryAudioResponse
  subclass of pydantic.BaseModel containing the path to the generated transcript.txt,
  summary.txt, and summary.mp3 files.
name: PodcastTranscriptionAndSummarization
parameters: {}
